// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Reflection;
    using Microsoft.VisualStudio.TextTemplating;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class MinimalApiTemplate : MinimalApiTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("var builder = WebApplication.CreateBuilder(args);\r\nvar app = builder.Build();\r\n\r\n" +
                    "\r\n");
            
            #line 14 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"

    foreach (var path in FileProperties) {
        Path = path.Key;
        foreach (var operation in FileProperties[Path]) {
            Method = operation.Key;

            ParametersList = operation.Value["parameters"];

            if (ParametersList != String.Empty) {
                ParametersList = ", " + ParametersList;
            }

            
            #line default
            #line hidden
            this.Write("app.");
            
            #line 26 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Method));
            
            #line default
            #line hidden
            this.Write("(\"");
            
            #line 26 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Path));
            
            #line default
            #line hidden
            this.Write("\", (HttpContext context");
            
            #line 26 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParametersList));
            
            #line default
            #line hidden
            this.Write(") =>\r\n{\r\n");
            
            #line 28 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"

            foreach (var response in operation.Value) {

                if (response.Key != "parameters") {
                    StatusCode = response.Key;
                    if (response.Value == "Default") {
                        var statusMethod = StatusCode switch {
                        "202" => "Accepted()",
                        "400" => "BadRequest()",
                        "409" => "Conflict()",
                        "204" => "NoContent()",
                        "404" => "NotFound()",
                        "200" => "Ok()",
                        "401" => "Unauthorized()",
                        "422" => "UnprocessableEntity()",
                        _ => $"StatusCode({response.Key})"
                        };
                        ReturnValue = $"Results.{statusMethod}";
                    }
                    else {
                        var statusMethod = StatusCode switch {
                        "202" => $"Accepted(_, {response.Value})",
                        "400" => $"BadRequest({response.Value})",
                        "409" => $"Conflict({response.Value})",
                        "204" => "NoContent()",
                        "404" => $"NotFound({response.Value})",
                        "200" => $"Ok({response.Value})",
                        "401" => "Unauthorized()",
                        "422" => $"UnprocessableEntity({response.Value})",
                        _ => $"StatusCode({response.Key})"
                        };
                        ReturnValue = $"Results.{statusMethod}";
                    }
                    
                }
                else {
                    continue;
                }

            
            #line default
            #line hidden
            this.Write("    if (context.Request.Headers[\"AcceptStatusCode\"] == \"");
            
            #line 67 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StatusCode));
            
            #line default
            #line hidden
            this.Write("\")\r\n    {\r\n        return ");
            
            #line 69 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ReturnValue));
            
            #line default
            #line hidden
            this.Write(";\r\n    }\r\n\r\n");
            
            #line 72 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"

            }

            
            #line default
            #line hidden
            this.Write("    return null;\r\n});\r\n\r\n");
            
            #line 78 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 83 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"

    foreach (var schema in Schemas) {
        UserObject = schema.Key;

            
            #line default
            #line hidden
            this.Write("public class ");
            
            #line 87 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UserObject));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 88 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"

        string constructorParameters = string.Empty;
        string constructorBody = string.Empty;
        foreach (var property in schema.Value) {
            PropertyName = property.Key;
            PropertyType = property.Value;
            constructorParameters += PropertyType + "? " + PropertyName + ", ";
            constructorBody += $"this.{PropertyName} = {PropertyName}\n";

            
            #line default
            #line hidden
            this.Write("    public ");
            
            #line 97 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PropertyType));
            
            #line default
            #line hidden
            this.Write("? ");
            
            #line 97 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PropertyName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 98 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"

        }
        ConstructorParameters = constructorParameters.Substring(0, constructorParameters.Length - 2);
        constructorBody = constructorBody.Substring(0, constructorBody.Length - 1);

            
            #line default
            #line hidden
            this.Write("    public ");
            
            #line 103 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UserObject));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 103 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ConstructorParameters));
            
            #line default
            #line hidden
            this.Write(") {\r\n");
            
            #line 104 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"

    var statements = constructorBody.Split("\n");
    foreach (var statement in statements) {
        ConstructorBody = statement;

            
            #line default
            #line hidden
            this.Write("       ");
            
            #line 109 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ConstructorBody));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 110 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("    }\r\n    public ");
            
            #line 114 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UserObject));
            
            #line default
            #line hidden
            this.Write("() {}\r\n}\r\n");
            
            #line 116 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 120 "C:\Users\AnhThiDao\AspLabs\src\OpenAPI\CodeGenerator\MinimalApiTemplate.tt"

    public Dictionary<string, Dictionary<string, Dictionary<string, string>>> FileProperties { get; set; }
    public string Path { get; set; }
    public string Method { get; set; }
    public string ReturnValue { get; set; }
    public string ParametersList { get; set; }
    public string StatusCode { get; set; }
    public Dictionary<string, Dictionary<string, string>> Schemas { get; set; }
    public string UserObject { get; set; }
    public string PropertyName { get; set; }
    public string PropertyType { get; set; }
    public string ConstructorParameters { get; set; }
    public string ConstructorBody { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class MinimalApiTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
