variables:
  - name: Build.Repository.Clean
    value: true
  - name: _TeamName
    value: AspNetCore
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: _HelixType
    value: build/product
  - name: _DotNetArtifactsCategory
    value: .NETCore

  # Variables for public PR builds
  - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
    - name: _HelixSource
      value: pr/aspnet/AspLabs/$(Build.SourceBranch)

  # Variables for internal Official builds
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - name: _HelixSource
      value: official/aspnet/AspLabs/$(Build.SourceBranch)

trigger:
- main

pr:
- "*"

stages:
- stage: build
  displayName: Build
  - template: /eng/templates/default-build.yml
