//HintName: OpenApiXmlCommentSupport.generated.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

namespace System.Runtime.CompilerServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.AspNetCore.OpenApi.SourceGenerators, Version=42.42.42.42, Culture=neutral, PublicKeyToken=adb9793829ddae60", "42.42.42.42")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : System.Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace Microsoft.AspNetCore.OpenApi.Generated
{
    using DocFx.XmlComments;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    using System.Text.Json;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.OpenApi;
    using Microsoft.AspNetCore.Mvc.Controllers;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.OpenApi.Models;
    using Microsoft.OpenApi.Any;

    file static class XmlCommentCache
    {
        private static Dictionary<(Type?, string?), string>? _cache;
        public static Dictionary<(Type?, string?), string> Cache
        {
            get
            {
                if (_cache is null)
                {
                    _cache = GenerateCacheEntries();
                }
                return _cache;
            }
        }

        private static Dictionary<(Type?, string?), string> GenerateCacheEntries()
        {
            var _cache = new Dictionary<(Type?, string?), string>();
            _cache.Add((typeof(global::TypeWithExamples), nameof(global::TypeWithExamples.BooleanType)), "{\"Summary\":null,\"Description\":null,\"Remarks\":null,\"Returns\":null,\"Examples\":[\"true\"]}");
            _cache.Add((typeof(global::TypeWithExamples), nameof(global::TypeWithExamples.IntegerType)), "{\"Summary\":null,\"Description\":null,\"Remarks\":null,\"Returns\":null,\"Examples\":[\"42\"]}");
            _cache.Add((typeof(global::TypeWithExamples), nameof(global::TypeWithExamples.LongType)), "{\"Summary\":null,\"Description\":null,\"Remarks\":null,\"Returns\":null,\"Examples\":[\"1234567890123456789\"]}");
            _cache.Add((typeof(global::TypeWithExamples), nameof(global::TypeWithExamples.DoubleType)), "{\"Summary\":null,\"Description\":null,\"Remarks\":null,\"Returns\":null,\"Examples\":[\"3.14\"]}");
            _cache.Add((typeof(global::TypeWithExamples), nameof(global::TypeWithExamples.FloatType)), "{\"Summary\":null,\"Description\":null,\"Remarks\":null,\"Returns\":null,\"Examples\":[\"3.14\"]}");
            _cache.Add((typeof(global::TypeWithExamples), nameof(global::TypeWithExamples.DecimalType)), "{\"Summary\":null,\"Description\":null,\"Remarks\":null,\"Returns\":null,\"Examples\":[\"3.14\"]}");
            _cache.Add((typeof(global::TypeWithExamples), nameof(global::TypeWithExamples.DateTimeType)), "{\"Summary\":null,\"Description\":null,\"Remarks\":null,\"Returns\":null,\"Examples\":[\"2022-01-01T00:00:00Z\"]}");
            _cache.Add((typeof(global::TypeWithExamples), nameof(global::TypeWithExamples.DateTimeOffsetType)), "{\"Summary\":null,\"Description\":null,\"Remarks\":null,\"Returns\":null,\"Examples\":[\"2022-01-01T00:00:00Z\"]}");
            _cache.Add((typeof(global::TypeWithExamples), nameof(global::TypeWithExamples.ByteArrayType)), "{\"Summary\":null,\"Description\":null,\"Remarks\":null,\"Returns\":null,\"Examples\":[\"SGVsbG8gV29ybGQ=\"]}");
            _cache.Add((typeof(global::TypeWithExamples), nameof(global::TypeWithExamples.ObjectType)), "{\"Summary\":null,\"Description\":null,\"Remarks\":null,\"Returns\":null,\"Examples\":[\"{ \\u0022a\\u0022 : 1, \\u0022b\\u0022: 3.14, \\u0022c\\u0022: \\u0022hello\\u0022 }\"]}");
            return _cache;

        }
    }

    file class XmlCommentOperationTransformer : IOpenApiOperationTransformer
    {
        public Task TransformAsync(OpenApiOperation operation, OpenApiOperationTransformerContext context, CancellationToken cancellationToken)
        {
            var methodInfo = context.Description.ActionDescriptor is ControllerActionDescriptor controllerActionDescriptor
                ? controllerActionDescriptor.MethodInfo
                : context.Description.ActionDescriptor.EndpointMetadata.OfType<MethodInfo>().SingleOrDefault();

            if (methodInfo is null)
            {
                return Task.CompletedTask;
            }
            System.Diagnostics.Debugger.Break();
            if (XmlCommentCache.Cache.TryGetValue((methodInfo.DeclaringType, methodInfo.Name), out var methodCommentString))
            {
                var methodComment = JsonSerializer.Deserialize<XmlComment>(methodCommentString);
                operation.Summary = methodComment.Summary;
                operation.Description = methodComment.Description;
                if (methodComment.Parameters is { Count: > 0 })
                {
                    foreach (var parameter in operation.Parameters)
                    {
                        var parameterInfo = methodInfo.GetParameters().SingleOrDefault(info => info.Name == parameter.Name);
                        var parameterComment = methodComment.Parameters.SingleOrDefault(xmlParameter => xmlParameter.Name == parameter.Name);
                        parameter.Description = parameterComment.Description;
                        parameter.Example = OpenApiExamplesHelper.ToOpenApiAny(parameterComment.Example, parameterInfo.ParameterType);
                    }
                }
                if (methodComment.Responses is { Count: > 0})
                {
                    foreach (var response in operation.Responses)
                    {
                        var responseComment = methodComment.Responses.SingleOrDefault(xmlResponse => xmlResponse.Code == response.Key);
                        response.Value.Description = responseComment.Description;
                    }
                }
            }

            return Task.CompletedTask;
        }
    }

    file class XmlCommentSchemaTransformer : IOpenApiSchemaTransformer
    {
        public Task TransformAsync(OpenApiSchema schema, OpenApiSchemaTransformerContext context, CancellationToken cancellationToken)
        {
            if (context.JsonPropertyInfo is { AttributeProvider: PropertyInfo propertyInfo })
            {
                if (XmlCommentCache.Cache.TryGetValue((propertyInfo.DeclaringType, propertyInfo.Name), out var propertyCommentString))
                {
                    var propertyComment = JsonSerializer.Deserialize<XmlComment>(propertyCommentString);
                    schema.Description = propertyComment.Returns ?? propertyComment.Summary;
                    if (propertyComment.Examples is { Count: > 0 })
                    {
                        schema.Example = OpenApiExamplesHelper.ToOpenApiAny(propertyComment.Examples.FirstOrDefault(), propertyInfo.PropertyType);
                    }
                }
            }
            if (XmlCommentCache.Cache.TryGetValue((context.JsonTypeInfo.Type, null), out var typeCommentString))
            {
                var typeComment = JsonSerializer.Deserialize<XmlComment>(typeCommentString);
                schema.Description = typeComment.Summary;
                if (typeComment.Examples is { Count: > 0 })
                {
                    schema.Example = OpenApiExamplesHelper.ToOpenApiAny(typeComment.Examples.FirstOrDefault(), context.JsonTypeInfo.Type);
                }
            }
            return Task.CompletedTask;
        }
    }

    file static class OpenApiExamplesHelper
    {
        public static IOpenApiAny ToOpenApiAny(string? example, Type type)
        {
            return Type.GetTypeCode(type) switch
            {
                TypeCode.String => new OpenApiString(example),
                TypeCode.Boolean => new OpenApiBoolean(bool.Parse(example)),
                TypeCode.Int32 => new OpenApiInteger(int.Parse(example)),
                TypeCode.Int64 => new OpenApiLong(long.Parse(example)),
                TypeCode.Double => new OpenApiDouble(double.Parse(example)),
                TypeCode.Single => new OpenApiFloat(float.Parse(example)),
                TypeCode.DateTime => new OpenApiDateTime(DateTime.Parse(example)),
                _ => new OpenApiNull()
            };
        }
    }

    file static class GeneratedServiceCollectionExtensions
    {
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GObiT5PdSNiK8u6txH/UK6MAAABQcm9ncmFtLmNz")]
        public static IServiceCollection AddOpenApi(this IServiceCollection services)
        {
            return services.AddOpenApi("v1", options =>
            {
                options.AddSchemaTransformer(new XmlCommentSchemaTransformer());
                options.AddOperationTransformer(new XmlCommentOperationTransformer());
            });
        }

    }
}