//HintName: OpenApiXmlCommentSupport.generated.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

namespace System.Runtime.CompilerServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.AspNetCore.OpenApi.SourceGenerators, Version=42.42.42.42, Culture=neutral, PublicKeyToken=adb9793829ddae60", "42.42.42.42")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : System.Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace Microsoft.AspNetCore.OpenApi.Generated
{
    using DocFx.XmlComments;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    using System.Text.Json;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.OpenApi;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.OpenApi.Models;
    using Microsoft.OpenApi.Any;

    file class XmlComment
    {
        public string? Summary { get; }
        public object? Example { get; }

        public XmlComment(string? summary, object? example)
        {
            Summary = summary;
            Example = example;
        }
    }

    file static class OpenApiAnyExtensions
    {
        public static IOpenApiAny ToOpenApiAny(this object? value)
        {
            if (value is null)
            {
                return new OpenApiNull();
            }
            if (value is bool boolValue)
            {
                return new OpenApiBoolean(boolValue);
            }
            if (value is int intValue)
            {
                return new OpenApiInteger(intValue);
            }
            if (value is long longValue)
            {
                return new OpenApiLong(longValue);
            }
            if (value is float floatValue)
            {
                return new OpenApiFloat(floatValue);
            }
            if (value is double doubleValue)
            {
                return new OpenApiDouble(doubleValue);
            }
            if (value is string stringValue)
            {
                return new OpenApiString(stringValue);
            }
            if (value is byte[] byteArrayValue)
            {
                return new OpenApiBinary(byteArrayValue);
            }
            if (value is System.DateTime dateTimeValue)
            {
                return new OpenApiDateTime(dateTimeValue);
            }
            if (value is System.DateTimeOffset dateTimeOffsetValue)
            {
                return new OpenApiDateTime(dateTimeOffsetValue);
            }
            if (value is System.Uri uriValue)
            {
                return new OpenApiString(uriValue.ToString());
            }
            if (value is System.Collections.IEnumerable enumerableValue)
            {
                var array = new OpenApiArray();
                foreach (var item in enumerableValue)
                {
                    array.Add(item.ToOpenApiAny());
                }
                return array;
            }
            return new OpenApiString(value.ToString());
        }
    }

    file class XmlCommentSchemaTransformer : IOpenApiSchemaTransformer
    {
        internal static readonly Dictionary<(Type, string?), XmlComment> Cache = new()
        {
            { (typeof(global::Todo), null), new XmlComment("This is a todo item.", null) },
            { (typeof(global::Project), null), new XmlComment("The project that contains <xref href=\"Todo\" data-throw-if-not-resolved=\"false\"></xref> items.", null) },
            { (typeof(global::Todo), nameof(global::Todo.Id)), new XmlComment("The ID of the todo item.", null) },
            { (typeof(global::Todo), nameof(global::Todo.Name)), new XmlComment("The name of the todo item.", null) },
            { (typeof(global::Todo), nameof(global::Todo.Description)), new XmlComment("The description of the todo item.", null) },
            { (typeof(global::Project), nameof(global::Project.Name)), new XmlComment("The name of the project.", null) },
            { (typeof(global::Project), nameof(global::Project.Description)), new XmlComment("The description of the project.", null) },

        };

        public Task TransformAsync(OpenApiSchema schema, OpenApiSchemaTransformerContext context, CancellationToken cancellationToken)
        {
            if (context.JsonPropertyInfo is { AttributeProvider: PropertyInfo propertyInfo })
            {
                if (System.Diagnostics.Debugger.IsAttached)
                {
                    System.Diagnostics.Debugger.Break();
                }
                if (Cache.TryGetValue((propertyInfo.DeclaringType, propertyInfo.Name), out var propertyComment))
                {
                    schema.Description = propertyComment.Summary;
                    if (propertyComment.Example is not null)
                    {
                        schema.Example = propertyComment.Example.ToOpenApiAny();
                    }
                }
            }
            if (Cache.TryGetValue((context.JsonTypeInfo.Type, null), out var typeComment))
            {
                schema.Description = typeComment.Summary;
                if (schema.Example is not null)
                {
                    schema.Example = typeComment.Example.ToOpenApiAny();
                }
            }
            return Task.CompletedTask;
        }
    }

    file static class GeneratedServiceCollectionExtensions
    {
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GekxtCsUq20KDXxGmUbZ5JUAAABQcm9ncmFtLmNz")]
        public static IServiceCollection AddOpenApi(this IServiceCollection services)
        {
            return services.AddOpenApi("v1", options =>
            {
                options.AddSchemaTransformer(new XmlCommentSchemaTransformer());
            });
        }

    }
}