//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNet.WebHooks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PusherReceiverResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PusherReceiverResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNet.WebHooks.Properties.PusherReceiverResources", typeof(PusherReceiverResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse Pusher WebHook data: {0}.
        /// </summary>
        internal static string Receiver_BadEvent {
            get {
                return ResourceManager.GetString("Receiver_BadEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; header value is invalid. It must be a valid hex-encoded string..
        /// </summary>
        internal static string Receiver_BadHeaderEncoding {
            get {
                return ResourceManager.GetString("Receiver_BadHeaderEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WebHook verification request must contain a &apos;{0}&apos; query parameter which will get echoed back in a successful response..
        /// </summary>
        internal static string Receiver_NoChallenge {
            get {
                return ResourceManager.GetString("Receiver_NoChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find any applications settings of the form &apos;{0}&apos;. To receive WebHooks from the &apos;{1}&apos; receiver, please add corresponding applications settings..
        /// </summary>
        internal static string Receiver_NoSecrets {
            get {
                return ResourceManager.GetString("Receiver_NoSecrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP header &apos;{0}&apos; value of &apos;{1}&apos; is not recognized as a valid application key. Please ensure that the right application keys and secrets have been configured..
        /// </summary>
        internal static string Receiver_SecretNotFound {
            get {
                return ResourceManager.GetString("Receiver_SecretNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application setting &apos;{0}&apos; must have a comma separated list of one or more values of the form &apos;&lt;appKey&gt;_&lt;appSecret&gt;&apos;..
        /// </summary>
        internal static string Recevier_BadSecret {
            get {
                return ResourceManager.GetString("Recevier_BadSecret", resourceCulture);
            }
        }
    }
}
