// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System;
using System.Globalization;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http.Controllers;
using Microsoft.AspNet.WebHooks.Properties;
using Newtonsoft.Json.Linq;

namespace Microsoft.AspNet.WebHooks
{
    /// <summary>
    /// Provides an <see cref="IWebHookReceiver"/> implementation which supports WebHooks generated by MyGet. 
    /// A sample WebHook URI is '<c>https://&lt;host&gt;/api/webhooks/incoming/myget/{id}?code=83699ec7c1d794c0c780e49a5c72972590571fd8</c>'.
    /// For security reasons the WebHook URI must be an <c>https</c> URI and contain a 'code' query parameter with the
    /// same value as configured in the '<c>MS_WebHookReceiverSecret_MyGet</c>' application setting.
    /// The 'code' parameter must be between 32 and 128 characters long.
    /// For details about MyGet WebHooks, see <c>http://docs.myget.org/docs/reference/webhooks</c>.
    /// </summary>
    public class MyGetWebHookReceiver : WebHookReceiver
    {
        internal const string ReceiverName = "myget";

        internal const string MediaType = "application/vnd.myget.webhooks.v1+json";
        internal const string PayloadTypePropertyName = "PayloadType";
        internal const string PingPayload = "PingWebHookEventPayloadV1";

        /// <inheritdoc />
        public override string Name
        {
            get { return ReceiverName; }
        }

        /// <inheritdoc />
        public override async Task<HttpResponseMessage> ReceiveAsync(string id, HttpRequestContext context, HttpRequestMessage request)
        {
            if (id == null)
            {
                throw new ArgumentNullException("id");
            }
            if (context == null)
            {
                throw new ArgumentNullException("context");
            }
            if (request == null)
            {
                throw new ArgumentNullException("request");
            }

            if (request.Method == HttpMethod.Post)
            {
                // Ensure that we use https and have a valid code parameter
                await EnsureValidCode(request, id);

                // Read the request entity body.
                JObject data = await ReadAsJsonAsync(request);

                // Read the action from data
                JToken action;
                string actionAsString;
                if (!data.TryGetValue(PayloadTypePropertyName, out action))
                {
                    string msg = string.Format(CultureInfo.CurrentCulture, MyGetReceiverResources.Receiver_NoEvent, PayloadTypePropertyName);
                    context.Configuration.DependencyResolver.GetLogger().Error(msg);
                    HttpResponseMessage noPayloadType = request.CreateErrorResponse(HttpStatusCode.BadRequest, msg);
                    return noPayloadType;
                }
                else
                {
                    actionAsString = action.Value<string>();
                }

                // If this is a ping request then just return. Otherwise call handlers.
                if (string.Equals(actionAsString, PingPayload, StringComparison.OrdinalIgnoreCase))
                {
                    context.Configuration.DependencyResolver.GetLogger().Info(MyGetReceiverResources.Receiver_PingEvent);
                    return request.CreateResponse();
                }
                return await ExecuteWebHookAsync(id, context, request, new[] { actionAsString }, data);
            }

            return CreateBadMethodResponse(request);
        }
    }
}
