// <auto-generated />
namespace Microsoft.AspNet.WebHooks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class WebHookStoreInitialDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WebHookStoreInitialDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201511060517479_WebHookStoreInitialDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
